# .github/workflows/ci.yaml

name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{secrets.PROJECT_ID}} --yes
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          npm run build
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --project ${{secrets.PROJECT_ID}} --yes

      - name: Upload artifact
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --project ${{secrets.PROJECT_ID}} --yes

      - name: Set release url
        id: get_release_url
        run: echo release_url="https://www.uniproject.jp" >> $GITHUB_OUTPUT

      - name: Faild Log
        if: failure()
        run: |
          if [ -s error.txt ]; then
            cat error.txt
            exit 1
          fi

      - name: Show Deployment URL
        run: |
          deploy_url=$(cat deployment-url.txt) >> $GITHUB_ENV
          echo "Deployment URL: $deploy_url"
