# .github/workflows/ci.yaml

name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run the script
        run: scripts/allbuild.sh

      - name: Copy src
        run: cp -r src/* output

      - name: Copy vercel.json
        run: cp vercel.json output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output

  prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: output
          path: ./output

      - name: Test
        run: tree output

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Link Vercel Project
        run: |
          cd output
          vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{secrets.PROJECT_ID}} --yes

      - name: Deploy with Vercel
        run: |
          cd output
          vercel deploy --prod -f --token=${{secrets.VERCEL_TOKEN}} >deployment-url.txt 2>error.txt

      - name: Set release url
        id: get_release_url
        run: echo release_url="https://www.uniproject.jp" >> $GITHUB_OUTPUT

      - name: Faild Log
        if: failure()
        run: |
          if [ -s error.txt ]; then
            cat error.txt
            exit 1
          fi

      - name: Show Deployment URL
        run: |
          deploy_url=$(cat deployment-url.txt) >> $GITHUB_ENV
          echo "Deployment URL: $deploy_url"
